### ISSUE TITLE
중간 보고서 checklist

### ISSUE THREAD

**Issue by lsjmc0224** [DGU-ISEmergency/Algorithms#5]
## 0. edge 생성
- [x] 왕복 4차로 (2차로 + 2차로)의 좌우 양방통행의 거리를 생성

## 1.1 차량 생성
- [x] 일정 확률로 차량을 생성함
    - 일단 차량은 동일한 놈들만 생성해보자
- [x] 응급차량도 같이 생성

## 1.2 신호 만들기
- [x] 초기 신호주기 일단 만들어야함.

## 2. 응급차량 감지 (detection)
- [x] 응급차량이 일정 확률로 생성되어 감지기에 감지되는 동작 구현
    - 감지기는 edge의 시작 부분에 있어야 시간을 계산할 수 있겠죠?

## 3. 신호 자동 변경
- [x] detection이 됐을 때, 대기행렬 소거시간 계산
- [x] 계산 완료 시 실제 신호에 반영

## 4. output xml파일로 저장하는 연습
- [x] 파일로 차량 1대별 delay, trip time 나오게 코드제작
